name: Compilacion del ejecutable Java con Maeven y subida a Docker Hub

on:
   push:
     branches:
       - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v3

    - name: set Up de JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Revisando cache de Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Construyendo con Maven
      run: mvn clean install -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Logeando en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Construyendo & pusheando Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          4lexander/aceleradora_utn:${{ github.run_number }}
          4lexander/aceleradora_utn:latest

          
